### PR TITLE
Cursor Lerp Smoothing

### PR DESCRIPTION
**Pull request by ewoudje**
Adds smoothing for cursor.
Its a simple lerp between the prev and newest packet. 
This means that the cursor is always acting 1 packet behind but this should be fine.

### CODE REVIEW

**Comment by RatDotRaw** [comment]
Looks good.

**Comment by polycone** [comment]
The main issue is that all data related to the position evaluation and the evaluation itself should not be in the player state (broken SRP - high maintainability cost).
The overall approach is good, a packet behind thing is acceptable I guess.
So, please consider to move the evaluation and its data into `DrawCursorComponent`.

**Review by polycone — CHANGES_REQUESTED** [review]
Please address this issue first: https://github.com/onimp/oni_multiplayer/pull/223#issuecomment-1686057803

**Comment by ewoudje** [comment]
> The main issue is that all data related to the position evaluation and the evaluation itself should not be in the player state (broken SRP - high maintainability cost). The overall approach is good, a packet behind thing is acceptable I guess. So, please consider to move the evaluation and its data into `DrawCursorComponent`.

Yea I can move the getter code to the drawing, the only problem is that the data has to be modified when receiving the packet.
I'm unsure how I could solve this cleanly.

**Comment by polycone** [comment]
That's a good question, I was thinking for a while, seems like the cursor time must be a part of the state for sure.
I think it's time to replace specific `CursorPosition` and create a new record `PlayerCursor` with `Position` and `Time` properties and replace `PlayerState.CursorPosition` with just `public PlayerCursor Cursor { get; set; } = new(...);` for example.
Then the time should be included in the `UpdateCursorPosition` command. I'm not sure if Unity's `Time.time` can be used tho, because it could be scaled. Maybe `DateTime.Now.Ticks` is more reliable.
Then you can detect changes based on time, store previous values and evaluate the position locally in the `DrawCursorComponent`.

Btw, thanks for the contribution! That's really nice to see🙂

**Review by polycone — APPROVED** [review]
Nice work👍

**Pull request merged**
